# Generated by Django 4.2.3 on 2023-07-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='dia_pagamento',
        ),
        migrations.AddField(
            model_name='contapagar',
            name='data_pagamento',
            field=models.DateField(default="1997-01-01"),
            preserve_default=False,
        ),
    ]
